### PR TITLE
first pass at htmlwidget improvements

### PR DESCRIPTION
**Pull request by timelyportfolio**
This pull includes a first pass at improvements to the `htmlwidget` interface for `datacomb`.  Some noticeable changes:

* move R package stuff to `./pkg` which will require the additional `subdir="pkg"` argument to `devtools::install_github("cmpolis/datacomb,subdir="pkg")` but allows us to separate the `R` stuff
* do some opinionated guessing to hopefully simplify usage on the part of the `R` user
* add some examples and documentation

see #1 for the full discussion and history

### CODE REVIEW

**Comment by cmpolis** [comment]
:+1: :+1: :+1: Really appreciate this; thank you!

**Comment by timelyportfolio** [comment]
You've done all the hard work.  Still a long way to go on the `R` side, but I love that with one-line an `R` user can make a `datacomb`, so we have a platform for iteration.  Happy to make this the `htmlwidget` of the week when you think ready for the very little publicity that I can muster.

**Comment by cmpolis** [comment]
Haha, yeah, it's pretty remarkable you can get such a rich interface w/ just a single line of `R`; thanks again! I put in a few small updates, fixes, updated the dir structure, readme and did some cleanup tonight. I think things are in a pretty good state to share- feel free to publicize whenever you'd like!

**Comment by timelyportfolio** [comment]
Everything works great/better after your merge and changes.  Will write a post this afternoon or tomorrow morning.

**Pull request merged**
